[build]
  base = "/"
  command = "npm run build:netlify"
  publish = "frontend/build"

[dev]
  command = "npm start"
  port = 8888
  publish = "frontend/public"
  targetPort = 3000
  framework = "create-react-app"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_API_URL = "https://api.dominiotech.com.br"

# API redirects to our single serverless function.
# Esta regra deve vir antes da regra geral do SPA para ser processada primeiro.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Regra geral para Single Page Application (SPA).
# Deve ser a última regra para capturar todas as outras rotas.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables template
[template.environment]
  DATABASE_URL = "postgresql://user:password@host/database"
  JWT_SECRET = "your-secret-key"
  OPENAI_API_KEY = "your-openai-key"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.dominiotech.com.br; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';" 