[build]
  command = "npm run build:netlify"
  functions = "netlify/functions"
  publish = "frontend/build"

[dev]
  command = "npm start"
  port = 8888
  publish = "frontend/public"
  targetPort = 3000
  framework = "create-react-app"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force --no-audit"
  NETLIFY_USE_YARN = "false"

# API redirects to our single serverless function.
# Esta regra deve vir antes da regra geral do SPA para ser processada primeiro.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Regra geral para Single Page Application (SPA).
# Deve ser a última regra para capturar todas as outras rotas.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables template
[template.environment]
  DATABASE_URL = "postgresql://user:password@host/database"
  JWT_SECRET = "your-secret-key"
  OPENAI_API_KEY = "your-openai-key"
  NODE_ENV = "production" 