[build]
  command = "npm run build"
  publish = "frontend/build"
  functions = "functions"

[dev]
  command = "npm run dev:frontend"
  port = 8999
  targetPort = 3000
  publish = "frontend/build"
  autoLaunch = true
  framework = "#custom"

[build.environment]
  NODE_ENV = "production"

[dev.environment]
  NODE_ENV = "development"
  DATABASE_URL = "postgresql://neondb_owner:npg_aj6KdeGg4QiO@ep-weathered-dream-acw41z52-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "chave_super_secreta_123"

[context.dev.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_aj6KdeGg4QiO@ep-weathered-dream-acw41z52-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"
  JWT_SECRET = "chave_super_secreta_123"
  NODE_ENV = "development"

# API redirects to our single serverless function.
# Esta regra deve vir antes da regra geral do SPA para ser processada primeiro.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Regra geral para Single Page Application (SPA).
# Deve ser a última regra para capturar todas as outras rotas.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables template
[template.environment]
  DATABASE_URL = "postgresql://user:password@host/database"
  JWT_SECRET = "your-secret-key"
  OPENAI_API_KEY = "your-openai-key"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"
    Content-Security-Policy = "default-src 'self' http://localhost:3000 http://localhost:8888 https://peppy-narwhal-64ff9e.netlify.app *.sa-east-1.aws.neon.tech; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' http://localhost:8888 http://localhost:3000 https://peppy-narwhal-64ff9e.netlify.app *.sa-east-1.aws.neon.tech;" 